# Generated by Django 4.1.13 on 2024-06-18 09:20

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_options_lesson_order_lesson_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
