# Generated by Django 4.1.13 on 2024-07-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_usercourserelation_completed_userlessonrelation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-released']},
        ),
        migrations.RemoveField(
            model_name='usercourserelation',
            name='comment',
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='review',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='userlessonrelation',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=250, null=True),
        ),
    ]
