# Generated by Django 4.1.13 on 2024-07-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_userlessonrelation_comment_lessoncomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourserelation',
            name='review',
        ),
    ]
