# Generated by Django 4.1.13 on 2024-07-03 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_lessoncomment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_percent',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='usercourserelation',
            name='completed_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
