# Generated by Django 4.1.13 on 2024-07-06 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_usercourserelation_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
