# Generated by Django 4.1.13 on 2024-07-07 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_course_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourserelation',
            name='review',
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user_course_relation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review', to='courses.usercourserelation')),
            ],
        ),
    ]
