# Generated by Django 4.1.13 on 2024-07-08 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_remove_usercourserelation_review_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourserelation',
            name='rate',
        ),
        migrations.AddField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=None, null=True),
        ),
    ]
