# Generated by Django 4.1.13 on 2024-07-08 10:28

from django.db import migrations, models
import learner.models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0002_profile_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=learner.models.path_to_profile_avatar),
        ),
    ]
