# Generated by Django 4.1.13 on 2024-07-08 11:04

from django.db import migrations
import imagekit.models.fields
import learner.models


class Migration(migrations.Migration):

    dependencies = [
        ('learner', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=learner.models.path_to_profile_avatar),
        ),
    ]
