services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./devlearn:/devlearn
    environment:
      - DB_HOST=db
      - DB_NAME=devlearn
      - DB_USER=devlearner
      - DB_PASS=05081992
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db

  db:
    image: postgres:16.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devlearn
      - POSTGRES_USER=devlearner
      - POSTGRES_PASSWORD=05081992

volumes:
  postgres_data:
