services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./devlearn:/devlearn
    environment:
      - DB_HOST=db
      - DB_NAME=devlearn
      - DB_USER=devlearner
      - DB_PASS=05081992
    
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

    depends_on:
      - db
      - redis

  db:
    image: postgres:16.3
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devlearn
      - POSTGRES_USER=devlearner
      - POSTGRES_PASSWORD=05081992
  
  redis:
    image: redis:7.2.5-alpine
    hostname: redis
  
  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker -l info -E
    volumes:
      - ./devlearn:/devlearn
    links:
      - redis
    depends_on:
      - redis
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=devlearn
      - DB_USER=devlearner
      - DB_PASS=05081992
  
  flower:
    build:
      context: .
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./devlearn:/devlearn
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"


volumes:
  postgres_data:
